name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        compiler: clang
        build-type: Debug
        options: -DCMAKE_CXX_FLAGS="-Werror"
