name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build cpp17 project
      uses: nicledomaS/cmake_build_action@v1
      with:
        # Git submodule update
        submodule_update: OFF # Default is OFF
        # Cmake args (example -D<ARG1>=value;-D<ARG1>=value)
        cmake_args: -DCMAKE_CXX_FLAGS="-Werror"
        # Run unit tests
        run_tests: ON # Default is OFF
        # Cmake arg for turn build unit test (if need)
        unit_test_build: ""
        # For multi-configuration tools, choose configuration <Release or Debug>
        config: Release # Default is Release
